# -*- coding: utf-8 -*-
"""MITRE_Tactic_BERT._gdelt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4hc2WLvePuGt1Z5FP_o4PsAxwedYZuW
"""

import pandas as pd
df = pd.read_csv('/content/Prova gdelt MITRE-SPARTA.csv')
df.head()

import pandas as pd
from openai import OpenAI
import time

# Your API token and base URL
client = OpenAI(
    api_key='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3OGI4NmFmLWVlNzUtNGE5Yy1hMDZlLTcyNzBiOTU5OTk3ZSIsImlzcyI6ImdwdGpyYyIsImlhdCI6MTczODIzNDg4OCwiZXhwIjoxNzQwNzAwODAwLCJpc19yZXZva2VkIjpmYWxzZSwiYWNjb3VudF9pZCI6ImQzYmVjNzQxLWFhNmItNDhjMC1iMjE1LTQyMWM2MmZmMWQ0ZCIsInVzZXJuYW1lIjoiRGFuaWVsZS5LQVNIQU5JLVJBREBleHQuZWMuZXVyb3BhLmV1IiwicHJvamVjdF9pZCI6IkVOQ0VSIiwiZGVwYXJ0bWVudCI6IkpSQy5FLjIiLCJxdW90YXMiOlt7Im1vZGVsX25hbWUiOiJncHQtNG8iLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTM1LXR1cmJvLTExMDYiLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTQtMTEwNiIsImV4cGlyYXRpb25fZnJlcXVlbmN5IjoiZGFpbHkiLCJ2YWx1ZSI6NDAwMDAwfV0sImFjY2Vzc19ncm91cHMiOlt7ImlkIjoiNWMzNGIzNWQtMjQxYy00NmM0LTg5MjAtNzBmYmJiNDEzZGQ2IiwiYWNjZXNzX2dyb3VwIjoiZ2VuZXJhbCJ9XX0.oBUY9bRglAgpHGTl6LVNVL839DjDPn6U2dCna2QQGPk',
    base_url="https://api-gpt.jrc.ec.europa.eu/v1"
)

# Load your dataset
df = pd.read_csv('/content/Prova gdelt MITRE-SPARTA.csv')

# Define a function to classify cyber attack or not
def classify_cyber_attack(text, start_time, time_limit=10):
    try:
        # Check if we've exceeded the time limit
        if time.time() - start_time > time_limit:
            print("Time limit exceeded. Stopping process.")
            return 0

        # Send request to OpenAI API for classification (Cyber Attack or Not)
        chat_completion = client.chat.completions.create(
            model="llama-3.3-70b-instruct",
            messages=[
                {"role": "system", "content": "You are a helpful assistant who classifies whether a given text is a cyber attack."},
                {"role": "user", "content": f"Please classify the following text as '1' if it represents a cyber attack or '0' if it does not: {text}"}
            ],
            stream=False,
            temperature=0.8
        )

        # Extract the response content
        response_content = chat_completion.choices[0].message.content
        print(f"API Response: {response_content}")  # Debugging print

        # Convert the response to an integer (either 0 or 1)
        if '1' in response_content.strip():
            return 1
        else:
            return 0

    except Exception as e:
        print(f"Error processing text: {text}, Error: {e}")
        return 0

# Function to process the dataset with time limit
def process_dataframe(df, time_limit=10):
    start_time = time.time()
    results = []

    # Process each row with time checking
    for index, row in df.iterrows():
        text = row['summary']
        result = classify_cyber_attack(text, start_time, time_limit)
        results.append(result)  # Append the result regardless of time limit

        # Check for time limit after processing each row, but don't break
        if time.time() - start_time > time_limit:
            print("Time limit exceeded, processing remaining rows with default value (0)")
            # Fill the remaining results with the default value
            remaining_rows = len(df) - len(results)
            results.extend([0] * remaining_rows)
            break # break loop if time is exceeding.

    # Add the new 'cyber_attack' column to the DataFrame
    df['cyber_attack'] = results

    return df

# Process the DataFrame with the time limit
df_processed = process_dataframe(df, time_limit=10)

# Save the processed DataFrame to a new CSV file
df_processed.to_csv('/content/Prova gdelt MITRE-SPARTA_with_cyber_attack.csv', index=False)

# Output the first few rows to verify
df_processed.head()

import pandas as pd
from openai import OpenAI
import time

# Your API token and base URL
client = OpenAI(
    api_key='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3OGI4NmFmLWVlNzUtNGE5Yy1hMDZlLTcyNzBiOTU5OTk3ZSIsImlzcyI6ImdwdGpyYyIsImlhdCI6MTczODIzNDg4OCwiZXhwIjoxNzQwNzAwODAwLCJpc19yZXZva2VkIjpmYWxzZSwiYWNjb3VudF9pZCI6ImQzYmVjNzQxLWFhNmItNDhjMC1iMjE1LTQyMWM2MmZmMWQ0ZCIsInVzZXJuYW1lIjoiRGFuaWVsZS5LQVNIQU5JLVJBREBleHQuZWMuZXVyb3BhLmV1IiwicHJvamVjdF9pZCI6IkVOQ0VSIiwiZGVwYXJ0bWVudCI6IkpSQy5FLjIiLCJxdW90YXMiOlt7Im1vZGVsX25hbWUiOiJncHQtNG8iLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTM1LXR1cmJvLTExMDYiLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTQtMTEwNiIsImV4cGlyYXRpb25fZnJlcXVlbmN5IjoiZGFpbHkiLCJ2YWx1ZSI6NDAwMDAwfV0sImFjY2Vzc19ncm91cHMiOlt7ImlkIjoiNWMzNGIzNWQtMjQxYy00NmM0LTg5MjAtNzBmYmJiNDEzZGQ2IiwiYWNjZXNzX2dyb3VwIjoiZ2VuZXJhbCJ9XX0.oBUY9bRglAgpHGTl6LVNVL839DjDPn6U2dCna2QQGPk',
    base_url="https://api-gpt.jrc.ec.europa.eu/v1"
)

# Load your dataset
df = pd.read_csv('/content/Prova gdelt MITRE-SPARTA_with_cyber_attack.csv')

# Define a function to classify threat or not
def classify_threat(text, start_time, time_limit=10):
    try:
        # Check if we've exceeded the time limit
        if time.time() - start_time > time_limit:
            print("Time limit exceeded. Stopping process.")
            return 0  # Default to 0 (no threat) if time limit exceeded

        # Send request to OpenAI API for classification (Threat or Not)
        chat_completion = client.chat.completions.create(
            model="llama-3.3-70b-instruct",
            messages=[
                {"role": "system", "content": "You are a helpful assistant who classifies whether a given text is a threat."},
                {"role": "user", "content": f"Please classify the following text as '1' if it represents a threat or '0' if it does not: {text}"}
            ],
            stream=False,
            temperature=0.8
        )

        # Extract the response content
        response_content = chat_completion.choices[0].message.content
        print(f"API Response: {response_content}")  # Debugging print

        # Convert the response to an integer (either 0 or 1)
        if '1' in response_content.strip():
            return 1
        else:
            return 0

    except Exception as e:
        print(f"Error processing text: {text}, Error: {e}")
        return 0  # Default to 0 (no threat) in case of error

# Function to process the dataset with time limit
def process_dataframe(df, time_limit=10):
    start_time = time.time()
    results = []

    # Process each row with time checking
    for index, row in df.iterrows():
        text = row['summary']
        result = classify_threat(text, start_time, time_limit) # Call classify_threat
        results.append(result)  # Append the result regardless of time limit

        # Check for time limit after processing each row, but don't break
        if time.time() - start_time > time_limit:
            print("Time limit exceeded, processing remaining rows with default value (0)")
            # Fill the remaining results with the default value
            remaining_rows = len(df) - len(results)
            results.extend([0] * remaining_rows)
            break # break loop if time is exceeding.

    # Add the new 'threat' column to the DataFrame
    df['threat'] = results  # Change column name to 'threat'

    return df

# Process the DataFrame with the time limit
df_processed = process_dataframe(df, time_limit=10)

# Save the processed DataFrame to a new CSV file
df_processed.to_csv('/content/Prova_gdelt_MITRE-SPARTA_with_threat.csv', index=False) # Change file name

# Output the first few rows to verify
df_processed.head()

!pip install pandas transformers torch

import pandas as pd
from transformers import pipeline, AutoModelForSequenceClassification

# Read the CSV file
df = pd.read_csv('/content/Prova_gdelt_MITRE-SPARTA_with_threat.csv')

from datasets import load_dataset

ds = load_dataset("tumeteor/Security-TTP-Mapping")

!pip install --upgrade tensorflow>=2.18.0

!pip install --upgrade "numpy<2.0" "transformers>=4.41.0,<5.0.0" "typing-extensions>=4.6"

!pip install pandas transformers datasets numpy
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import numpy as np

# Load the model and tokenizer
model_id = "sarahwei/MITRE-tactic-bert-case-based"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSequenceClassification.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,
    # device_map="auto",  # Optional: Use if you have multiple GPUs
)

# Load the CSV file
csv_file = "/content/Prova_gdelt_MITRE-SPARTA_with_threat.csv"
df = pd.read_csv(csv_file)

# Process only the first 700 rows
df_subset = df.head(700)  # Select the first 700 rows

# Function to classify text (unchanged)
def classify_text(text):
    # Truncate the input text to the maximum sequence length
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
    outputs = model(**inputs)
    logits = outputs.logits
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(logits.squeeze().cpu())
    predictions = np.zeros(probs.shape)
    predictions[np.where(probs >= 0.5)] = 1
    predicted_labels = [model.config.id2label[idx] for idx, label in enumerate(predictions) if label == 1.0]
    return predicted_labels  # Return the list of predicted labels

# Apply classification to the 'description' column of the subset
df_subset['predicted_tactics'] = df_subset['summary'].apply(classify_text)

# Print the subset DataFrame with the classification results
print(df_subset[['summary', 'predicted_tactics']])

# Save the results to a new CSV file
output_csv_file = "gdelt_with_predictions.csv"  # Choose your desired output file name
df_subset.to_csv(output_csv_file, index=False)

df_subset.head()

import pandas as pd

# Read the CSV file into a pandas DataFrame
df = pd.read_csv('MITRE_TACTIC_selected.csv')

# Display the first few rows of the DataFrame
df.head()

import pandas as pd
from google.colab import files
from openai import OpenAI
import re
import time

# Your API token and base URL
# Your API token and base URL
client = OpenAI(
    api_key='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3OGI4NmFmLWVlNzUtNGE5Yy1hMDZlLTcyNzBiOTU5OTk3ZSIsImlzcyI6ImdwdGpyYyIsImlhdCI6MTczODIzNDg4OCwiZXhwIjoxNzQwNzAwODAwLCJpc19yZXZva2VkIjpmYWxzZSwiYWNjb3VudF9pZCI6ImQzYmVjNzQxLWFhNmItNDhjMC1iMjE1LTQyMWM2MmZmMWQ0ZCIsInVzZXJuYW1lIjoiRGFuaWVsZS5LQVNIQU5JLVJBREBleHQuZWMuZXVyb3BhLmV1IiwicHJvamVjdF9pZCI6IkVOQ0VSIiwiZGVwYXJ0bWVudCI6IkpSQy5FLjIiLCJxdW90YXMiOlt7Im1vZGVsX25hbWUiOiJncHQtNG8iLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTM1LXR1cmJvLTExMDYiLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTQtMTEwNiIsImV4cGlyYXRpb25fZnJlcXVlbmN5IjoiZGFpbHkiLCJ2YWx1ZSI6NDAwMDAwfV0sImFjY2Vzc19ncm91cHMiOlt7ImlkIjoiNWMzNGIzNWQtMjQxYy00NmM0LTg5MjAtNzBmYmJiNDEzZGQ2IiwiYWNjZXNzX2dyb3VwIjoiZ2VuZXJhbCJ9XX0.oBUY9bRglAgpHGTl6LVNVL839DjDPn6U2dCna2QQGPk',
    base_url="https://api-gpt.jrc.ec.europa.eu/v1"
)

# Load your dataset (replace 'your_dataset.csv' with the name of your file)
df = pd.read_csv('gdelt_selected_predictions.csv')  # Replace with your actual CSV filename

# Function to provide detailed contextual prompt for Impact techniques
def teach_impact_structure_with_context():
    prompt = """
    The MITRE ATT&CK framework includes techniques under the Impact tactic (TA0040), which refers to adversaries trying to manipulate, interrupt, or destroy systems and data. Below are the techniques related to Impact, along with their descriptions:

    1. **Account Access Removal (T1531)**:
       Adversaries may interrupt availability of system and network resources by inhibiting access to accounts utilized by legitimate users. Accounts may be deleted, locked, or manipulated (ex: changed credentials) to remove access to accounts. Adversaries may also subsequently log off and/or perform a System Shutdown/Reboot to set malicious changes into place.

    2. **Data Destruction (T1485)**:
       Adversaries may destroy data and files on specific systems or in large numbers on a network to interrupt availability to systems, services, and network resources. Data destruction is likely to render stored data irrecoverable by forensic techniques through overwriting files or data on local and remote drives. Common operating system file deletion commands such as del and rm often only remove pointers to files without wiping the contents of the files themselves, making the files recoverable by proper forensic methodology. This behavior is distinct from Disk Content Wipe and Disk Structure Wipe because individual files are destroyed rather than sections of a storage disk or the disk's logical structure.

    3. **Lifecycle-Triggered Deletion (T1485.001)**:
       Adversaries may modify the lifecycle policies of a cloud storage bucket to destroy all objects stored within.

    4. **Data Encrypted for Impact (T1486)**:
       Adversaries may encrypt data on target systems or on large numbers of systems in a network to interrupt availability to system and network resources. They can attempt to render stored data inaccessible by encrypting files or data on local and remote drives and withholding access to a decryption key. This may be done in order to extract monetary compensation from a victim in exchange for decryption or a decryption key (ransomware) or to render data permanently inaccessible in cases where the key is not saved or transmitted.

    5. **Data Manipulation (T1565)**:
       Adversaries may insert, delete, or manipulate data in order to influence external outcomes or hide activity, thus threatening the integrity of the data. By manipulating data, adversaries may attempt to affect a business process, organizational understanding, or decision making.

    6. **Defacement (T1491)**:
       Adversaries may modify visual content available internally or externally to an enterprise network, thus affecting the integrity of the original content. Reasons for Defacement include delivering messaging, intimidation, or claiming (possibly false) credit for an intrusion. Disturbing or offensive images may be used as a part of Defacement in order to cause user discomfort, or to pressure compliance with accompanying messages.

    7. **Disk Wipe (T1561)**:
       Adversaries may wipe or corrupt raw disk data on specific systems or in large numbers in a network to interrupt availability to system and network resources. With direct write access to a disk, adversaries may attempt to overwrite portions of disk data. Adversaries may opt to wipe arbitrary portions of disk data and/or wipe disk structures like the master boot record (MBR). A complete wipe of all disk sectors may be attempted.

    8. **Endpoint Denial of Service (T1499)**:
       Adversaries may perform Endpoint Denial of Service (DoS) attacks to degrade or block the availability of services to users. Endpoint DoS can be performed by exhausting the system resources those services are hosted on or exploiting the system to cause a persistent crash condition. Example services include websites, email services, DNS, and web-based applications. Adversaries have been observed conducting DoS attacks for political purposes and to support other malicious activities, including distraction, hacktivism, and extortion.

    9. **Firmware Corruption (T1495)**:
       Adversaries may overwrite or corrupt the flash memory contents of system BIOS or other firmware in devices attached to a system in order to render them inoperable or unable to boot, thus denying the availability to use the devices and/or the system. Firmware is software that is loaded and executed from non-volatile memory on hardware devices in order to initialize and manage device functionality. These devices may include the motherboard, hard drive, or video cards.

    10. **Inhibit System Recovery (T1490)**:
        Adversaries may delete or remove built-in data and turn off services designed to aid in the recovery of a corrupted system to prevent recovery. This may deny access to available backups and recovery options.

    11. **Network Denial of Service (T1498)**:
        Adversaries may perform Network Denial of Service (DoS) attacks to degrade or block the availability of targeted resources to users. Network DoS can be performed by exhausting the network bandwidth services rely on. Example resources include specific websites, email services, DNS, and web-based applications. Adversaries have been observed conducting network DoS attacks for political purposes and to support other malicious activities, including distraction, hacktivism, and extortion.

    12. **Service Stop (T1489)**:
        Adversaries may stop or disable services on a system to render those services unavailable to legitimate users. Stopping critical services or processes can inhibit or stop response to an incident or aid in the adversary's overall objectives to cause damage to the environment.

    13. **System Shutdown/Reboot (T1529)**:
        Adversaries may shutdown/reboot systems to interrupt access to, or aid in the destruction of, those systems. Operating systems may contain commands to initiate a shutdown/reboot of a machine or network device. In some cases, these commands may also be used to initiate a shutdown/reboot of a remote computer or network device via Network Device CLI (e.g. reload).

    Now, analyze the following description and determine which techniques and sub-techniques apply to the **Impact (TA0040)** tactic:

    Description: {description}
    Predicted Tactics: {predicted_tactics}
    """
    return prompt


# Function to process each row in the DataFrame and analyze Impact techniques and sub-techniques
def analyze_impact_techniques(row):
    try:
        summary = row['summary']  # Use 'summary' column instead of 'description'
        predicted_tactics = row['predicted_tactics']

        # Check if the predicted tactics column contains "Impact"
        if "Impact" in predicted_tactics:
            # Create the prompt for Impact techniques
            prompt = teach_impact_structure_with_context()

            # Send the request to OpenAI's API for analysis (assuming `client` is configured)
            chat_completion = client.chat.completions.create(
                model="llama-3.3-70b-instruct",  # Using your desired model
                messages=[{"role": "system", "content": "You are a helpful assistant specializing in cybersecurity and the MITRE ATT&CK framework."},
                          {"role": "user", "content": prompt.format(description=summary, predicted_tactics=predicted_tactics)}],
                stream=False,
                temperature=0.7,
                timeout=30  # Set timeout to 30 seconds to prevent long runs or crashes
            )

            # Extract the result (summary of techniques and sub-techniques)
            response = chat_completion.choices[0].message.content

            # Extract techniques and sub-techniques for the Impact tactics (e.g., "Data Destruction (T1485)")
            techniques = []
            matched_techniques = re.findall(r'\b[A-Za-z\s]+\s\((T\d+)\)', response)
            for match in matched_techniques:
                if match not in techniques:
                    techniques.append(match)

            # Format output for techniques (only technique name and code)
            techniques_column = ' / '.join([f"{technique}" for technique in techniques])

            # Return the result for the DataFrame
            return techniques_column.strip()

        # If the tactic is not "Impact," return an empty string
        return ""

    except Exception as e:
        print(f"Error analyzing text: {e}")
        return ""  # Return an empty string in case of error


# Apply the function to the DataFrame to analyze each row
df['techniques'] = df.apply(analyze_impact_techniques, axis=1)

# Save the results to a new CSV file
df.to_csv('gdelt_MITRE_IMPACT_TECHNIQUES3.csv', index=False)

# Optionally, download the file directly in Google Colab
files.download('gdelt_MITRE_IMPACT_TECHNIQUES3.csv')

import pandas as pd

# Read the CSV file
df = pd.read_csv('gdelt_MITRE_IMPACT_TECHNIQUES3.csv')

# Define a dictionary to map technique codes to their names
technique_mapping = {
    "T1531": "Account Access Removal",
    "T1485": "Data Destruction",
    "T1485.001": "Lifecycle-Triggered Deletion",
    "T1486": "Data Encrypted for Impact",
    "T1565": "Data Manipulation",
    "T1491": "Defacement",
    "T1561": "Disk Wipe",
    "T1499": "Endpoint Denial of Service",
    "T1495": "Firmware Corruption",
    "T1490": "Inhibit System Recovery",
    "T1498": "Network Denial of Service",
    "T1489": "Service Stop",
    "T1529": "System Shutdown/Reboot"
}


# Function to extract technique names from codes
def get_technique_names(codes_string):
    # Check if the value is a string before attempting to split
    if isinstance(codes_string, str):
        codes = codes_string.split(" / ")
        names = [technique_mapping.get(code, code) for code in codes]
        return " / ".join(names)
    else:
        return ""  # Or any other default value for non-string values

# Apply the function to create the new column
df['techniques names'] = df['techniques'].apply(get_technique_names)


# Save the updated DataFrame to a new CSV file
df.to_csv('gdelt_MITRE_IMPACT_names_TECHNIQUES3.csv', index=False)

# Print the first few rows to verify the changes
print(df.head())

import pandas as pd
from google.colab import files
from openai import OpenAI
import re
import time

# Your API token and base URL
# Your API token and base URL
client = OpenAI(
    api_key='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3OGI4NmFmLWVlNzUtNGE5Yy1hMDZlLTcyNzBiOTU5OTk3ZSIsImlzcyI6ImdwdGpyYyIsImlhdCI6MTczODIzNDg4OCwiZXhwIjoxNzQwNzAwODAwLCJpc19yZXZva2VkIjpmYWxzZSwiYWNjb3VudF9pZCI6ImQzYmVjNzQxLWFhNmItNDhjMC1iMjE1LTQyMWM2MmZmMWQ0ZCIsInVzZXJuYW1lIjoiRGFuaWVsZS5LQVNIQU5JLVJBREBleHQuZWMuZXVyb3BhLmV1IiwicHJvamVjdF9pZCI6IkVOQ0VSIiwiZGVwYXJ0bWVudCI6IkpSQy5FLjIiLCJxdW90YXMiOlt7Im1vZGVsX25hbWUiOiJncHQtNG8iLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTM1LXR1cmJvLTExMDYiLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTQtMTEwNiIsImV4cGlyYXRpb25fZnJlcXVlbmN5IjoiZGFpbHkiLCJ2YWx1ZSI6NDAwMDAwfV0sImFjY2Vzc19ncm91cHMiOlt7ImlkIjoiNWMzNGIzNWQtMjQxYy00NmM0LTg5MjAtNzBmYmJiNDEzZGQ2IiwiYWNjZXNzX2dyb3VwIjoiZ2VuZXJhbCJ9XX0.oBUY9bRglAgpHGTl6LVNVL839DjDPn6U2dCna2QQGPk',
    base_url="https://api-gpt.jrc.ec.europa.eu/v1"
)

# Load your dataset (replace 'your_dataset.csv' with the name of your file)
df = pd.read_csv('gdelt_MITRE_IMPACT_names_TECHNIQUES3.csv')  # Replace with your actual CSV filename

import re

# Function to provide detailed contextual prompt for Impact techniques
def teach_impact_structure_with_context():
    prompt = """
    Impact - TA0040
    Impact consists of techniques that adversaries use to disrupt availability or compromise integrity by manipulating business and operational processes. The adversary is trying to damage the system security, interrupting its normal execution, or damaging it physically. Due to the impossibility to reach the resource and repair/reprogram it, if the damage is too severe the resource is definitively lost. The damage can be at data level, targeting the stored or transmitted data, deleting them, or modifying them to deceive the receiver. It can be also at service level, interrupting a payload execution or hitting the communication with jamming and flooding to prevent it. Damage can be also at hardware level, destroying the space resource with electromagnetic power, kinetic weapons, or malicious hardware preinserted in the system.

    Techniques

    ID    |  Name                              | Description
    ----------------------------------------------------------------------
    T2054  | Data Manipulation                   | Adversaries may insert, delete, or manipulate data in order to influence external outcomes or hide activity, thus threatening the integrity of the data. By manipulating data, adversaries may attempt to affect a business process, organizational understanding, or decision making.

    T2054.001 | Stored Data Manipulation           | TBD

    T2054.002 | Transmitted Data Manipulation      | An attacker can modify transmitted data, jamming or overpowering the original signal and retransmitting a modified copy to the receiver, to command a spacecraft or to lead the system owner to erroneous decision.

    T2054.003 | Runtime Data Manipulation          | An attacker can use a controlled payload software or component to manipulate data during execution if a MMU or MPU is not implemented or misconfigured.

    T2050  | Ground Segment Jamming              | An attacker can jam the communication to prevent data being delivered.

    T2050.001 | Jamming from the ground           | TBD

    T2055  | Loss of spacecraft telecommanding   | An attacker can interrupt the communication link between a ground station and a spacecraft.

    T2055.001 | Replacement of authentication keys  | An attacker can replace the authentication keys (e.g SDLS session keys) to disconnect the legitimate ground station and potentially hijack the connection.

    T2027  | Permanent loss to telecommand satellite | An attacker can perform actions that permanently leave the owner without control on the space resource.

    T2027.001 | Replace session and master keys     | Adversaries can replace session and master keys in a space resource to gain permanent access to the resource.

    T2028  | Resource damage                     | An attacker can attempt to damage a space resource to cause a mission loss.

    T2028.004 | Space Debris Impact                | A space resource is damaged or destroyed if impacted with space debris.

    T2028.005 | Physical sabotage                  | An attacker can physically damage a satellite using harmful commands or attacking it with another vehicle.

    T2028.007 | Intentional collision with other satellites | Adversaries can command the satellite to collide with other satellites.

    T2028.009 | Destruction of sensors               | TBD

    T2028.010 | Destruction of receivers            | TBD

    T2028.011 | Breakdown of counterfeit components  | A space resource can be damaged by counterfeit or faulty components.

    T2028.012 | Kinetic attacks                    | Attackers can use anti-satellite missiles or other kinetic energy threats to attack a resource.

    T1496  | Resource Hijacking                  | An attacker can hijack resources of the space vehicle.

    T2052  | Saturation of Inter Satellite Links | An attack aiming to flood the network can saturate the intersatellite link.

    T2052.001 | Coremelt attacks                   | TBD

    T2053  | Saturation/Exhaustion of Spacecraft Resources | An attacker can target satellites with energy/resource constraints to prioritize power saving efforts.

    T2053.001 | Receiver flooding                   | An attacker can flood the spacecraft receiver sending large amounts of data.

    T2053.002 | Avionics Bus Flooding               | TBD

    T2053.003 | OBC overloading                     | TBD

    T2053.004 | Drain satellite's power            | An attacker can target satellites with energy or resource constraints to consume their energy.

    T2053.005 | Waste of propellant                 | An attacker can maliciously consume satellite propellant resources to reduce satellite life.

    T1489  | Service Stop                        | An attacker can interrupt services, disabling them or taking control over them.

    T1489.001 | Ground system loss                 | The ground facility can be disabled or taken control of via cyber or physical attack.

    T1489.002 | Disabling Payload Service          | An attacker can disable the payload or parts of it, leveraging TC switch on-off commands.

    T2049  | Spacecraft Jamming                  | If the victim uses over-the-air communication, it can be threatened by jamming attacks.

    T2049.001 | Receiver lock on a spurious carrier  | The lock of the spacecraft receiver or ground station with a continuous wave or DSSS sequence can be a threat.

    T2049.002 | Optical Jamming (Links/Sensor Blinding) | An attacker can conduct optical attacks with high power laser beams to target optical sensors or links.

    T2049.003 | SDR buffer overflow                 | Insufficient checks in radio frame processing could lead to buffer overflows, creating denial-of-service conditions.

    T2026  | Temporary loss to telecommand satellite | An attacker can temporarily leave the owner without control over the space resource.

    T2026.001 | Replace session keys               | Adversaries can replace encryption keys to gain permanent access or temporarily interrupt control.

    T2024  | Transmitted Data Manipulation       | An attacker can modify transmitted data to command a spacecraft or lead the system's owner to an erroneous decision.
    """
    return prompt


# Function to check if the summary is related to the space segment
def is_space_related(summary):
    space_keywords = ['space', 'satellite', 'orbital', 'payload', 'satcom']
    for keyword in space_keywords:
        if re.search(r'\b' + re.escape(keyword) + r'\b', summary, re.IGNORECASE):
            return True
    return False


# Function to check if the 'predicted_tactics' column is Impact and process the row
def analyze_impact_techniques(row):
    try:
        summary = row['summary']  # Use 'summary' column instead of 'description'
        predicted_tactics = row['predicted_tactics']  # Check the 'predicted_tactics' column

        if 'Impact' in predicted_tactics:
            if is_space_related(summary):
                # Return relevant technique codes for Impact
                impact_techniques = [
                    "T2054", "T2054.001", "T2054.002", "T2054.003", "T2050", "T2050.001",
                    "T2055", "T2055.001", "T2027", "T2027.001", "T2028", "T2028.004",
                    "T2028.005", "T2028.007", "T2028.009", "T2028.010", "T2028.011",
                    "T2028.012", "T1496", "T2052", "T2052.001", "T2053", "T2053.001",
                    "T2053.002", "T2053.003", "T2053.004", "T2053.005", "T1489",
                    "T1489.001", "T1489.002", "T2049", "T2049.001", "T2049.002",
                    "T2049.003", "T2026", "T2026.001", "T2024"
                ]
                return ', '.join(impact_techniques)  # Return list of relevant techniques
            else:
                return "No relevant space-related techniques found."
        else:
            return "Not Impact-related"
    except Exception as e:
        return f"Error processing row: {e}"


# Apply the analysis function to the DataFrame and create a new column for the responses
df['ESA_techniques'] = df.apply(analyze_impact_techniques, axis=1)

# Save the updated dataframe to a new CSV file
df.to_csv('gdelt_impact_analysis_with_ESA3.csv', index=False)

# Optionally, download the CSV file
files.download('gdelt_impact_analysis_with_ESA3.csv')

#prova due specificando se relativo a space segment, satellite o communication links usando ESA

import pandas as pd
from google.colab import files
from openai import OpenAI
import re
import time

# Your API token and base URL
# Your API token and base URL
client = OpenAI(
    api_key='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3OGI4NmFmLWVlNzUtNGE5Yy1hMDZlLTcyNzBiOTU5OTk3ZSIsImlzcyI6ImdwdGpyYyIsImlhdCI6MTczODIzNDg4OCwiZXhwIjoxNzQwNzAwODAwLCJpc19yZXZva2VkIjpmYWxzZSwiYWNjb3VudF9pZCI6ImQzYmVjNzQxLWFhNmItNDhjMC1iMjE1LTQyMWM2MmZmMWQ0ZCIsInVzZXJuYW1lIjoiRGFuaWVsZS5LQVNIQU5JLVJBREBleHQuZWMuZXVyb3BhLmV1IiwicHJvamVjdF9pZCI6IkVOQ0VSIiwiZGVwYXJ0bWVudCI6IkpSQy5FLjIiLCJxdW90YXMiOlt7Im1vZGVsX25hbWUiOiJncHQtNG8iLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTM1LXR1cmJvLTExMDYiLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTQtMTEwNiIsImV4cGlyYXRpb25fZnJlcXVlbmN5IjoiZGFpbHkiLCJ2YWx1ZSI6NDAwMDAwfV0sImFjY2Vzc19ncm91cHMiOlt7ImlkIjoiNWMzNGIzNWQtMjQxYy00NmM0LTg5MjAtNzBmYmJiNDEzZGQ2IiwiYWNjZXNzX2dyb3VwIjoiZ2VuZXJhbCJ9XX0.oBUY9bRglAgpHGTl6LVNVL839DjDPn6U2dCna2QQGPk',
    base_url="https://api-gpt.jrc.ec.europa.eu/v1"
)


# Load your dataset (replace 'your_dataset.csv' with the name of your file)
df = pd.read_csv('gdelt_MITRE_IMPACT_names_TECHNIQUES3.csv')  # Replace with your actual CSV filename


import re

# Function to provide detailed contextual prompt for Impact techniques
def teach_impact_structure_with_context():
    prompt = """
    Impact - TA0040
    Impact consists of techniques that adversaries use to disrupt availability or compromise integrity by manipulating business and operational processes. The adversary is trying to damage the system security, interrupting its normal execution, or damaging it physically. Due to the impossibility to reach the resource and repair/reprogram it, if the damage is too severe the resource is definitively lost. The damage can be at data level, targeting the stored or transmitted data, deleting them, or modifying them to deceive the receiver. It can be also at service level, interrupting a payload execution or hitting the communication with jamming and flooding to prevent it. Damage can be also at hardware level, destroying the space resource with electromagnetic power, kinetic weapons, or malicious hardware preinserted in the system.

    Techniques

    ID    |  Name                              | Description
    ----------------------------------------------------------------------
    T2054  | Data Manipulation                   | Adversaries may insert, delete, or manipulate data in order to influence external outcomes or hide activity, thus threatening the integrity of the data. By manipulating data, adversaries may attempt to affect a business process, organizational understanding, or decision making.

    T2054.001 | Stored Data Manipulation           | TBD

    T2054.002 | Transmitted Data Manipulation      | An attacker can modify transmitted data, jamming or overpowering the original signal and retransmitting a modified copy to the receiver, to command a spacecraft or to lead the system owner to erroneous decision.

    T2054.003 | Runtime Data Manipulation          | An attacker can use a controlled payload software or component to manipulate data during execution if a MMU or MPU is not implemented or misconfigured.

    T2050  | Ground Segment Jamming              | An attacker can jam the communication to prevent data being delivered.

    T2050.001 | Jamming from the ground           | TBD

    T2055  | Loss of spacecraft telecommanding   | An attacker can interrupt the communication link between a ground station and a spacecraft.

    T2055.001 | Replacement of authentication keys  | An attacker can replace the authentication keys (e.g SDLS session keys) to disconnect the legitimate ground station and potentially hijack the connection.

    T2027  | Permanent loss to telecommand satellite | An attacker can perform actions that permanently leave the owner without control on the space resource.

    T2027.001 | Replace session and master keys     | Adversaries can replace session and master keys in a space resource to gain permanent access to the resource.

    T2028  | Resource damage                     | An attacker can attempt to damage a space resource to cause a mission loss.

    T2028.004 | Space Debris Impact                | A space resource is damaged or destroyed if impacted with space debris.

    T2028.005 | Physical sabotage                  | An attacker can physically damage a satellite using harmful commands or attacking it with another vehicle.

    T2028.007 | Intentional collision with other satellites | Adversaries can command the satellite to collide with other satellites.

    T2028.009 | Destruction of sensors               | TBD

    T2028.010 | Destruction of receivers            | TBD

    T2028.011 | Breakdown of counterfeit components  | A space resource can be damaged by counterfeit or faulty components.

    T2028.012 | Kinetic attacks                    | Attackers can use anti-satellite missiles or other kinetic energy threats to attack a resource.

    T1496  | Resource Hijacking                  | An attacker can hijack resources of the space vehicle.

    T2052  | Saturation of Inter Satellite Links | An attack aiming to flood the network can saturate the intersatellite link.

    T2052.001 | Coremelt attacks                   | TBD

    T2053  | Saturation/Exhaustion of Spacecraft Resources | An attacker can target satellites with energy/resource constraints to prioritize power saving efforts.

    T2053.001 | Receiver flooding                   | An attacker can flood the spacecraft receiver sending large amounts of data.

    T2053.002 | Avionics Bus Flooding               | TBD

    T2053.003 | OBC overloading                     | TBD

    T2053.004 | Drain satellite's power            | An attacker can target satellites with energy or resource constraints to consume their energy.

    T2053.005 | Waste of propellant                 | An attacker can maliciously consume satellite propellant resources to reduce satellite life.

    T1489  | Service Stop                        | An attacker can interrupt services, disabling them or taking control over them.

    T1489.001 | Ground system loss                 | The ground facility can be disabled or taken control of via cyber or physical attack.

    T1489.002 | Disabling Payload Service          | An attacker can disable the payload or parts of it, leveraging TC switch on-off commands.

    T2049  | Spacecraft Jamming                  | If the victim uses over-the-air communication, it can be threatened by jamming attacks.

    T2049.001 | Receiver lock on a spurious carrier  | The lock of the spacecraft receiver or ground station with a continuous wave or DSSS sequence can be a threat.

    T2049.002 | Optical Jamming (Links/Sensor Blinding) | An attacker can conduct optical attacks with high power laser beams to target optical sensors or links.

    T2049.003 | SDR buffer overflow                 | Insufficient checks in radio frame processing could lead to buffer overflows, creating denial-of-service conditions.

    T2026  | Temporary loss to telecommand satellite | An attacker can temporarily leave the owner without control over the space resource.

    T2026.001 | Replace session keys               | Adversaries can replace encryption keys to gain permanent access or temporarily interrupt control.

    T2024  | Transmitted Data Manipulation       | An attacker can modify transmitted data to command a spacecraft or lead the system's owner to an erroneous decision.
    """
    return prompt


# Function to check if the summary is related to the space segment
def is_space_related(summary):
    space_keywords = ['space', 'satellite', 'orbital', 'payload', 'satcom', 'telecommand', 'ground station', 'inter-satellite link', 'satellite communication']
    for keyword in space_keywords:
        if re.search(r'\b' + re.escape(keyword) + r'\b', summary, re.IGNORECASE):
            return True
    return False


# Function to check if the 'predicted_tactics' column is Impact and process the row
def analyze_impact_techniques(row):
    try:
        summary = row['summary']  # Use 'summary' column instead of 'description'
        predicted_tactics = row['predicted_tactics']  # Check the 'predicted_tactics' column

        if 'Impact' in predicted_tactics:
            if is_space_related(summary):
                # Return relevant technique codes for Impact
                impact_techniques = [
                    "T2054", "T2054.001", "T2054.002", "T2054.003", "T2050", "T2050.001",
                    "T2055", "T2055.001", "T2027", "T2027.001", "T2028", "T2028.004",
                    "T2028.005", "T2028.007", "T2028.009", "T2028.010", "T2028.011",
                    "T2028.012", "T1496", "T2052", "T2052.001", "T2053", "T2053.001",
                    "T2053.002", "T2053.003", "T2053.004", "T2053.005", "T1489",
                    "T1489.001", "T1489.002", "T2049", "T2049.001", "T2049.002",
                    "T2049.003", "T2026", "T2026.001", "T2024"
                ]
                return ', '.join(impact_techniques)  # Return list of relevant techniques
            else:
                return "No relevant space-related techniques found."
        else:
            return "Not Impact-related"
    except Exception as e:
        return f"Error processing row: {e}"


# Apply the analysis function to the DataFrame and create a new column for the responses
df['ESA_techniques'] = df.apply(analyze_impact_techniques, axis=1)

# Save the updated dataframe to a new CSV file
df.to_csv('5gdelt_impact_analysis_with_ESA.csv', index=False)

# Optionally, download the CSV file
from google.colab import files
files.download('5gdelt_impact_analysis_with_ESA.csv')

#prova 3 perchè ho notato che non avevo usato i llm x l analisi di contesto, ma le keywords e non voglio:

import pandas as pd
from google.colab import files
from openai import OpenAI
import re
import time

# Your API token and base URL
# Your API token and base URL
client = OpenAI(
    api_key='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3OGI4NmFmLWVlNzUtNGE5Yy1hMDZlLTcyNzBiOTU5OTk3ZSIsImlzcyI6ImdwdGpyYyIsImlhdCI6MTczODIzNDg4OCwiZXhwIjoxNzQwNzAwODAwLCJpc19yZXZva2VkIjpmYWxzZSwiYWNjb3VudF9pZCI6ImQzYmVjNzQxLWFhNmItNDhjMC1iMjE1LTQyMWM2MmZmMWQ0ZCIsInVzZXJuYW1lIjoiRGFuaWVsZS5LQVNIQU5JLVJBREBleHQuZWMuZXVyb3BhLmV1IiwicHJvamVjdF9pZCI6IkVOQ0VSIiwiZGVwYXJ0bWVudCI6IkpSQy5FLjIiLCJxdW90YXMiOlt7Im1vZGVsX25hbWUiOiJncHQtNG8iLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTM1LXR1cmJvLTExMDYiLCJleHBpcmF0aW9uX2ZyZXF1ZW5jeSI6ImRhaWx5IiwidmFsdWUiOjQwMDAwMH0seyJtb2RlbF9uYW1lIjoiZ3B0LTQtMTEwNiIsImV4cGlyYXRpb25fZnJlcXVlbmN5IjoiZGFpbHkiLCJ2YWx1ZSI6NDAwMDAwfV0sImFjY2Vzc19ncm91cHMiOlt7ImlkIjoiNWMzNGIzNWQtMjQxYy00NmM0LTg5MjAtNzBmYmJiNDEzZGQ2IiwiYWNjZXNzX2dyb3VwIjoiZ2VuZXJhbCJ9XX0.oBUY9bRglAgpHGTl6LVNVL839DjDPn6U2dCna2QQGPk',
    base_url="https://api-gpt.jrc.ec.europa.eu/v1"
)

# Load your dataset (replace 'your_dataset.csv' with the name of your file)
df = pd.read_csv('/content/6gdelt_impact_analysis_with_ESA_techniques_names_updated.csv')  # Replace with your actual CSV filename


import re

# Function to provide detailed contextual prompt for Impact techniques
def teach_impact_structure_with_context():
    prompt = """
    Impact - TA0040
    Impact consists of techniques that adversaries use to disrupt availability or compromise integrity by manipulating business and operational processes. The adversary is trying to damage the system security, interrupting its normal execution, or damaging it physically. Due to the impossibility to reach the resource and repair/reprogram it, if the damage is too severe the resource is definitively lost. The damage can be at data level, targeting the stored or transmitted data, deleting them, or modifying them to deceive the receiver. It can be also at service level, interrupting a payload execution or hitting the communication with jamming and flooding to prevent it. Damage can be also at hardware level, destroying the space resource with electromagnetic power, kinetic weapons, or malicious hardware preinserted in the system.

    Techniques

    ID    |  Name                              | Description
    ----------------------------------------------------------------------
    T2054  | Data Manipulation                   | Adversaries may insert, delete, or manipulate data in order to influence external outcomes or hide activity, thus threatening the integrity of the data. By manipulating data, adversaries may attempt to affect a business process, organizational understanding, or decision making.

    T2054.001 | Stored Data Manipulation           | TBD

    T2054.002 | Transmitted Data Manipulation      | An attacker can modify transmitted data, jamming or overpowering the original signal and retransmitting a modified copy to the receiver, to command a spacecraft or to lead the system owner to erroneous decision.

    T2054.003 | Runtime Data Manipulation          | An attacker can use a controlled payload software or component to manipulate data during execution if a MMU or MPU is not implemented or misconfigured.

    T2050  | Ground Segment Jamming              | An attacker can jam the communication to prevent data being delivered.

    T2050.001 | Jamming from the ground           | TBD

    T2055  | Loss of spacecraft telecommanding   | An attacker can interrupt the communication link between a ground station and a spacecraft.

    T2055.001 | Replacement of authentication keys  | An attacker can replace the authentication keys (e.g SDLS session keys) to disconnect the legitimate ground station and potentially hijack the connection.

    T2027  | Permanent loss to telecommand satellite | An attacker can perform actions that permanently leave the owner without control on the space resource.

    T2027.001 | Replace session and master keys     | Adversaries can replace session and master keys in a space resource to gain permanent access to the resource.

    T2028  | Resource damage                     | An attacker can attempt to damage a space resource to cause a mission loss.

    T2028.004 | Space Debris Impact                | A space resource is damaged or destroyed if impacted with space debris.

    T2028.005 | Physical sabotage                  | An attacker can physically damage a satellite using harmful commands or attacking it with another vehicle.

    T2028.007 | Intentional collision with other satellites | Adversaries can command the satellite to collide with other satellites.

    T2028.009 | Destruction of sensors               | TBD

    T2028.010 | Destruction of receivers            | TBD

    T2028.011 | Breakdown of counterfeit components  | A space resource can be damaged by counterfeit or faulty components.

    T2028.012 | Kinetic attacks                    | Attackers can use anti-satellite missiles or other kinetic energy threats to attack a resource.

    T1496  | Resource Hijacking                  | An attacker can hijack resources of the space vehicle.

    T2052  | Saturation of Inter Satellite Links | An attack aiming to flood the network can saturate the intersatellite link.

    T2052.001 | Coremelt attacks                   | TBD

    T2053  | Saturation/Exhaustion of Spacecraft Resources | An attacker can target satellites with energy/resource constraints to prioritize power saving efforts.

    T2053.001 | Receiver flooding                   | An attacker can flood the spacecraft receiver sending large amounts of data.

    T2053.002 | Avionics Bus Flooding               | TBD

    T2053.003 | OBC overloading                     | TBD

    T2053.004 | Drain satellite's power            | An attacker can target satellites with energy or resource constraints to consume their energy.

    T2053.005 | Waste of propellant                 | An attacker can maliciously consume satellite propellant resources to reduce satellite life.

    T1489  | Service Stop                        | An attacker can interrupt services, disabling them or taking control over them.

    T1489.001 | Ground system loss                 | The ground facility can be disabled or taken control of via cyber or physical attack.

    T1489.002 | Disabling Payload Service          | An attacker can disable the payload or parts of it, leveraging TC switch on-off commands.

    T2049  | Spacecraft Jamming                  | If the victim uses over-the-air communication, it can be threatened by jamming attacks.

    T2049.001 | Receiver lock on a spurious carrier  | The lock of the spacecraft receiver or ground station with a continuous wave or DSSS sequence can be a threat.

    T2049.002 | Optical Jamming (Links/Sensor Blinding) | An attacker can conduct optical attacks with high power laser beams to target optical sensors or links.

    T2049.003 | SDR buffer overflow                 | Insufficient checks in radio frame processing could lead to buffer overflows, creating denial-of-service conditions.

    T2026  | Temporary loss to telecommand satellite | An attacker can temporarily leave the owner without control over the space resource.

    T2026.001 | Replace session keys               | Adversaries can replace encryption keys to gain permanent access or temporarily interrupt control.

    T2024  | Transmitted Data Manipulation       | An attacker can modify transmitted data to command a spacecraft or lead the system's owner to an erroneous decision.
    """
    return prompt


# Function to process each row in the DataFrame and analyze Impact techniques and sub-techniques
def analyze_impact_techniques(row):
    try:
        summary = row['summary']  # Use 'summary' column instead of 'description'
        predicted_tactics = row['predicted_tactics']

        # Check if the predicted tactics column contains "Impact"
        if "Impact" in predicted_tactics:
            # Create the prompt for Impact techniques
            prompt = teach_impact_structure_with_context()

            # Send the request to OpenAI's API for analysis (assuming `client` is configured)
            chat_completion = client.chat.completions.create(
                model="llama-3.3-70b-instruct",  # Using your desired model
                messages=[{"role": "system", "content": "You are a helpful assistant specializing in cybersecurity and the MITRE ATT&CK framework."},
                          {"role": "user", "content": prompt.format(description=summary, predicted_tactics=predicted_tactics)}],
                stream=False,
                temperature=0.7,
                timeout=30  # Set timeout to 30 seconds to prevent long runs or crashes
            )

            # Extract the result (summary of techniques and sub-techniques)
            response = chat_completion.choices[0].message.content

            # Extract techniques and sub-techniques for the Impact tactics (e.g., "Data Destruction (T1485)")
            techniques = []
            matched_techniques = re.findall(r'\b[A-Za-z\s]+\s\((T\d+)\)', response)
            for match in matched_techniques:
                if match not in techniques:
                    techniques.append(match)

            # Format output for techniques (only technique name and code)
            techniques_column = ' / '.join([f"{technique}" for technique in techniques])

            # Return the result for the DataFrame
            return techniques_column.strip()

        # If the tactic is not "Impact," return an empty string
        return ""

    except Exception as e:
        print(f"Error analyzing text: {e}")
        return ""  # Return an empty string in case of error


# Apply the function to the DataFrame to analyze each row
df['esa_2_techniques'] = df.apply(analyze_impact_techniques, axis=1)

# Save the results to a new CSV file
df.to_csv('gdelt_esa_LLM.csv', index=False)

# Optionally, download the file directly in Google Colab
files.download('gdelt_esa_LLM.csv')

df.head()

import pandas as pd

# Load the CSV file
df = pd.read_csv('gdelt_esa_LLM.csv')

# Mapping of technique codes to their textual names
technique_name_mapping = {
    "T2054": "Data Manipulation",
    "T2054.001": "Stored Data Manipulation",
    "T2054.002": "Transmitted Data Manipulation",
    "T2054.003": "Runtime Data Manipulation",
    "T2050": "Ground Segment Jamming",
    "T2050.001": "Jamming from the ground",
    "T2055": "Loss of spacecraft telecommanding",
    "T2055.001": "Replacement of authentication keys",
    "T2027": "Permanent loss to telecommand satellite",
    "T2027.001": "Replace session and master keys",
    "T2028": "Resource damage",
    "T2028.004": "Space Debris Impact",
    "T2028.005": "Physical sabotage",
    "T2028.007": "Intentional collision with other satellites",
    "T2028.009": "Destruction of sensors",
    "T2028.010": "Destruction of receivers",
    "T2028.011": "Breakdown of counterfeit components",
    "T2028.012": "Kinetic attacks",
    "T1496": "Resource Hijacking",
    "T2052": "Saturation of Inter Satellite Links",
    "T2052.001": "Coremelt attacks",
    "T2053": "Saturation/Exhaustion of Spacecraft Resources",
    "T2053.001": "Receiver flooding",
    "T2053.002": "Avionics Bus Flooding",
    "T2053.003": "OBC overloading",
    "T2053.004": "Drain satellite's power",
    "T2053.005": "Waste of propellant",
    "T1489": "Service Stop",
    "T1489.001": "Ground system loss",
    "T1489.002": "Disabling Payload Service",
    "T2049": "Spacecraft Jamming",
    "T2049.001": "Receiver lock on a spurious carrier",
    "T2049.002": "Optical Jamming (Links/Sensor Blinding)",
    "T2049.003": "SDR buffer overflow",
    "T2026": "Temporary loss to telecommand satellite",
    "T2026.001": "Replace session keys",
    "T2024": "Transmitted Data Manipulation"
}

# Function to map technique codes to their names
def map_technique_codes_to_names(technique_codes):
    if technique_codes and isinstance(technique_codes, str):  # Check if it's a string before splitting
        technique_codes_list = technique_codes.split(', ')
        technique_names = [technique_name_mapping.get(code, 'Unknown Technique') for code in technique_codes_list]
        return ', '.join(technique_names)
    return ""  # Return empty string for non-string values

# Apply the mapping function to the ESA_techniques column to generate the new ESA_techniques_names column
df['ESA2_techniques_names'] = df['esa_2_techniques'].apply(map_technique_codes_to_names)
# Save the updated dataframe to a new CSV file
df.to_csv('2gdelt_esa_LLM.csv', index=False)

# Optionally, download the updated CSV file
from google.colab import files
files.download('2gdelt_esa_LLM.csv')

df.head()















