# -*- coding: utf-8 -*-
"""From extraction to llm fragmented classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/
"""

import pandas as pd

!pip install newspaper3k==0.2.8

!pip install lxml[html_clean]

from openai import OpenAI
import pandas as pd

# Your API token and base URL
client = OpenAI(
    api_key='your api',
    base_url="https://api-gpt.jrc.ec.europa.eu/v1"
)

# Load your dataset
df = pd.read_csv('c.150_newspaper_no_duplicates.csv')

def summarize_text(text):
    try:
        chat_completion = client.chat.completions.create(
            model="llama-3.3-70b-instruct",
            messages=[
                {"role": "system", "content": "You are a helpful and harmless AI assistant."},
                {"role": "user", "content": f"Please provide a concise summary of the following text: {text}"}
            ],
            stream=False,
            temperature=0.8
        )
        summary = chat_completion.choices[0].message.content
        return summary
    except Exception as e:
        print(f"Error summarizing text: {e}")
        return ""  # Return an empty string in case of error

# Apply the function to the "text" column
df['summary'] = df['text'].apply(summarize_text)

# Print the DataFrame with the new column
print(df)

from openai import OpenAI
import pandas as pd
import re
import time

# Your API token and base URL
client = OpenAI(
    api_key='your api',
    base_url="https://api-gpt.jrc.ec.europa.eu/v1"
)

# Load your dataset
df = pd.read_csv('c.150_newspaper_with_attack_type.csv')

# Check if the 'attack_type' column exists. If not, create it with empty strings
if 'attack_type' not in df.columns:
    df['attack_type'] = ''  # Initialize with empty strings

# Check if the 'summary' column exists. If not, create it with empty strings
if 'summary' not in df.columns:
    df['summary'] = ''  # Initialize with empty strings

def categorize_attack_type(text):
    try:
        chat_completion = client.chat.completions.create(
            model="llama-3.3-70b-instruct",
            messages=[
                {"role": "system", "content": "You are a helpful and harmless AI assistant."},
                {"role": "user", "content": f"""
Categorize the attack type of the following text: {text}
Only provide the attack type, without any additional context or explanation.
For example, instead of saying "The attack type of the text is Phishing", simply respond with "Phishing".
"""}
            ],
            stream=False,
            temperature=0.8
        )
        attack_type = chat_completion.choices[0].message.content.strip()

        # Remove contextual phrases using regex (optional)
        attack_type = re.sub(r"the attack type (?:of the text )?is\s*", "", attack_type, flags=re.IGNORECASE)
        attack_type = attack_type.strip()  # Strip again to remove any leading/trailing spaces

        return attack_type
    except Exception as e:
        if "429" in str(e):  # Check for rate limit error
            print("Rate limit exceeded. Waiting for 60 seconds...")
            time.sleep(60)  # Wait for 60 seconds
            return categorize_attack_type(text)  # Retry the request
        else:
            print(f"Error categorizing attack type: {e}")
            return ""

def summarize_text(text):
    try:
        chat_completion = client.chat.completions.create(
            model="llama-3.3-70b-instruct",
            messages=[
                {"role": "system", "content": "You are a helpful and harmless AI assistant."},
                {"role": "user", "content": f"Please provide a concise summary of the following text: {text}"}
            ],
            stream=False,
            temperature=0.8
        )
        summary = chat_completion.choices[0].message.content
        return summary
    except Exception as e:
        if "429" in str(e):  # Check for rate limit error
            print("Rate limit exceeded. Waiting for 60 seconds...")
            time.sleep(60)  # Wait for 60 seconds
            return summarize_text(text)  # Retry the request
        else:
            print(f"Error summarizing text: {e}")
            return ""

# Apply the functions only to rows where the respective columns are empty
df.loc[df['attack_type'] == '', 'attack_type'] = df.loc[df['attack_type'] == '', 'text'].apply(categorize_attack_type)
df.loc[df['summary'] == '', 'summary'] = df.loc[df['summary'] == '', 'text'].apply(summarize_text)

# Print the DataFrame with the new columns
print(df)



